# Generated by Django 3.0.5 on 2020-04-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_auto_20200424_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='distributer_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.IntegerField(null=True),
        ),
    ]
