# Generated by Django 3.0.5 on 2020-04-24 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
